---
id: 3cfd1174-d05a-4968-8973-4e1c8bbe9dfa
---
flowchart TD
    A[Holiday] -->|Find destinations| B(Find cities)
    B --> C{Let me think}
    C -->|One| D[Europe]
    C -->|Two| E[Asia]
    C -->|Three| F[South America]
    D -->|find flights and hotels| G(prioritise by cheapest options)